# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    # Configuration des sessions
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: false
        cookie_samesite: lax
        cookie_httponly: true
        storage_factory_id: session.storage.factory.native
        cookie_domain: null
        gc_maxlifetime: 3600
        name: SYNDIC_SESSION
        cookie_path: /

    # Autorisation de tous les domaines pour débloquer l'accès
    trusted_hosts: ['.*']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
