<?php

namespace ContainerNUEDUhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenueDepenseCrudControllerformatTextDataService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ywxHPS.App\Controller\Admin\MenueDepenseCrudController::formatTextData()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ywxHPS.App\\Controller\\Admin\\MenueDepenseCrudController::formatTextData()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityInstance' => ['privates', '.errored..service_locator.8ywxHPS.App\\Entity\\MenueDepense', NULL, 'Cannot autowire service ".service_locator.8ywxHPS": it needs an instance of "App\\Entity\\MenueDepense" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'entityInstance' => 'App\\Entity\\MenueDepense',
        ]))->withContext('App\\Controller\\Admin\\MenueDepenseCrudController::formatTextData()', $container);
    }
}
