<?php

namespace ContainerNUEDUhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockSuffisantValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\StockSuffisantValidator' shared autowired service.
     *
     * @return \App\Validator\StockSuffisantValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'StockSuffisantValidator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Validator\\StockSuffisantValidator'])) {
            return $container->privates['App\\Validator\\StockSuffisantValidator'];
        }

        $instance = new \App\Validator\StockSuffisantValidator($a);

        if (isset($container->privates['App\\Validator\\StockSuffisantValidator'])) {
            return $container->privates['App\\Validator\\StockSuffisantValidator'];
        }

        return $container->privates['App\\Validator\\StockSuffisantValidator'] = $instance;
    }
}
