<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUKTXxpy\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUKTXxpy/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerUKTXxpy.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerUKTXxpy\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerUKTXxpy\App_KernelProdDebugContainer([
    'container.build_hash' => 'UKTXxpy',
    'container.build_id' => '84698710',
    'container.build_time' => 1773863208,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUKTXxpy');
