<?php

namespace ContainerUKTXxpy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBatimentCrudControllerService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\BatimentCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\BatimentCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Trait/CoproprieteSecuriteTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/BatimentCrudController.php';

        $instance = new \App\Controller\Admin\BatimentCrudController();

        if (isset($container->services['App\\Controller\\Admin\\BatimentCrudController'])) {
            return $container->services['App\\Controller\\Admin\\BatimentCrudController'];
        }

        $container->services['App\\Controller\\Admin\\BatimentCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.WOU_dzL'] ?? $container->load('get_ServiceLocator_WOUDzLService'))->withContext('App\\Controller\\Admin\\BatimentCrudController', $container));

        return $instance;
    }
}
