<?php

namespace ContainerUKTXxpy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeCrudControllerService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\BadgeCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\BadgeCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Trait/CoproprieteSecuriteTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/BadgeCrudController.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->services['App\\Controller\\Admin\\BadgeCrudController'])) {
            return $container->services['App\\Controller\\Admin\\BadgeCrudController'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Controller\\Admin\\BadgeCrudController'])) {
            return $container->services['App\\Controller\\Admin\\BadgeCrudController'];
        }

        $instance = new \App\Controller\Admin\BadgeCrudController($a, (isset($container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']) ? $container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']($container) : self::getAdminUrlGeneratorService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $b);

        if (isset($container->services['App\\Controller\\Admin\\BadgeCrudController'])) {
            return $container->services['App\\Controller\\Admin\\BadgeCrudController'];
        }

        $container->services['App\\Controller\\Admin\\BadgeCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.WOU_dzL'] ?? $container->load('get_ServiceLocator_WOUDzLService'))->withContext('App\\Controller\\Admin\\BadgeCrudController', $container));

        return $instance;
    }
}
