<?php

namespace ContainerCDqeRHR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenueDepenseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8ywxHPS.App\Entity\MenueDepense' shared service.
     *
     * @return \App\Entity\MenueDepense
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8ywxHPS": it needs an instance of "App\\Entity\\MenueDepense" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
