<?php

namespace ContainerTocDLyg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncidentTypeService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Form\IncidentType' shared autowired service.
     *
     * @return \App\Form\IncidentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/IncidentType.php';

        return $container->privates['App\\Form\\IncidentType'] = new \App\Form\IncidentType();
    }
}
