<?php

namespace ContainerTocDLyg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllergetBatimentsByCoproService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.Uru1vV..App\Controller\RegistrationController::getBatimentsByCopro()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uru1vV..App\\Controller\\RegistrationController::getBatimentsByCopro()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'batimentRepo' => ['privates', 'App\\Repository\\BatimentRepository', 'getBatimentRepositoryService', true],
        ], [
            'batimentRepo' => 'App\\Repository\\BatimentRepository',
        ]))->withContext('App\\Controller\\RegistrationController::getBatimentsByCopro()', $container);
    }
}
