<?php

namespace ContainerTocDLyg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResidentControllerService extends App_KernelProdDebugContainer
{
    /**
     * Gets the public 'App\Controller\ResidentController' shared autowired service.
     *
     * @return \App\Controller\ResidentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ResidentController.php';

        $container->services['App\\Controller\\ResidentController'] = $instance = new \App\Controller\ResidentController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ResidentController', $container));

        return $instance;
    }
}
