<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNqZWG8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNqZWG8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNqZWG8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNqZWG8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNqZWG8\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNqZWG8',
    'container.build_id' => 'f9917fa6',
    'container.build_time' => 1774886505,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNqZWG8');
