<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRlyNKXJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRlyNKXJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRlyNKXJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRlyNKXJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRlyNKXJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'RlyNKXJ',
    'container.build_id' => '495440e9',
    'container.build_time' => 1774910746,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRlyNKXJ');
