<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNUEDUhx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNUEDUhx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNUEDUhx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNUEDUhx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNUEDUhx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NUEDUhx',
    'container.build_id' => '41633d05',
    'container.build_time' => 1774866690,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNUEDUhx');
