<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Copropriete extends \App\Entity\Copropriete implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'batiments' => [parent::class, 'batiments', null, 16],
        "\0".parent::class."\0".'codePostal' => [parent::class, 'codePostal', null, 16],
        "\0".parent::class."\0".'documents' => [parent::class, 'documents', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'menueDepenses' => [parent::class, 'menueDepenses', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'photos' => [parent::class, 'photos', null, 16],
        "\0".parent::class."\0".'prestataires' => [parent::class, 'prestataires', null, 16],
        "\0".parent::class."\0".'stockBadges' => [parent::class, 'stockBadges', null, 16],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'batiments' => [parent::class, 'batiments', null, 16],
        'codePostal' => [parent::class, 'codePostal', null, 16],
        'documents' => [parent::class, 'documents', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'menueDepenses' => [parent::class, 'menueDepenses', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'photos' => [parent::class, 'photos', null, 16],
        'prestataires' => [parent::class, 'prestataires', null, 16],
        'stockBadges' => [parent::class, 'stockBadges', null, 16],
        'ville' => [parent::class, 'ville', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
