<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lot extends \App\Entity\Lot implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annexes' => [parent::class, 'annexes', null, 16],
        "\0".parent::class."\0".'badges' => [parent::class, 'badges', null, 16],
        "\0".parent::class."\0".'batiment' => [parent::class, 'batiment', null, 16],
        "\0".parent::class."\0".'etage' => [parent::class, 'etage', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'locataire' => [parent::class, 'locataire', null, 16],
        "\0".parent::class."\0".'numeroLot' => [parent::class, 'numeroLot', null, 16],
        "\0".parent::class."\0".'parentLot' => [parent::class, 'parentLot', null, 16],
        "\0".parent::class."\0".'porte' => [parent::class, 'porte', null, 16],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null, 16],
        "\0".parent::class."\0".'tantieme' => [parent::class, 'tantieme', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'annexes' => [parent::class, 'annexes', null, 16],
        'badges' => [parent::class, 'badges', null, 16],
        'batiment' => [parent::class, 'batiment', null, 16],
        'etage' => [parent::class, 'etage', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'locataire' => [parent::class, 'locataire', null, 16],
        'numeroLot' => [parent::class, 'numeroLot', null, 16],
        'parentLot' => [parent::class, 'parentLot', null, 16],
        'porte' => [parent::class, 'porte', null, 16],
        'proprietaire' => [parent::class, 'proprietaire', null, 16],
        'tantieme' => [parent::class, 'tantieme', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
