<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Badge extends \App\Entity\Badge implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'couleur' => [parent::class, 'couleur', null, 16],
        "\0".parent::class."\0".'dateActivation' => [parent::class, 'dateActivation', null, 16],
        "\0".parent::class."\0".'dateRemplacement' => [parent::class, 'dateRemplacement', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lot' => [parent::class, 'lot', null, 16],
        "\0".parent::class."\0".'motifRemplacement' => [parent::class, 'motifRemplacement', null, 16],
        "\0".parent::class."\0".'numeroHexa' => [parent::class, 'numeroHexa', null, 16],
        "\0".parent::class."\0".'photos' => [parent::class, 'photos', null, 16],
        "\0".parent::class."\0".'remplacebadge' => [parent::class, 'remplacebadge', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'couleur' => [parent::class, 'couleur', null, 16],
        'dateActivation' => [parent::class, 'dateActivation', null, 16],
        'dateRemplacement' => [parent::class, 'dateRemplacement', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lot' => [parent::class, 'lot', null, 16],
        'motifRemplacement' => [parent::class, 'motifRemplacement', null, 16],
        'numeroHexa' => [parent::class, 'numeroHexa', null, 16],
        'photos' => [parent::class, 'photos', null, 16],
        'remplacebadge' => [parent::class, 'remplacebadge', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
