<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'copropriete' => [parent::class, 'copropriete', null, 16],
        "\0".parent::class."\0".'documents' => [parent::class, 'documents', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'horairesGardien' => [parent::class, 'horairesGardien', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'incidentsDeclares' => [parent::class, 'incidentsDeclares', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'lotsLoues' => [parent::class, 'lotsLoues', null, 16],
        "\0".parent::class."\0".'lotsPossedes' => [parent::class, 'lotsPossedes', null, 16],
        "\0".parent::class."\0".'menueDepenses' => [parent::class, 'menueDepenses', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'photos' => [parent::class, 'photos', null, 16],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'statutOccupation' => [parent::class, 'statutOccupation', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'copropriete' => [parent::class, 'copropriete', null, 16],
        'documents' => [parent::class, 'documents', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'horairesGardien' => [parent::class, 'horairesGardien', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'incidentsDeclares' => [parent::class, 'incidentsDeclares', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'lotsLoues' => [parent::class, 'lotsLoues', null, 16],
        'lotsPossedes' => [parent::class, 'lotsPossedes', null, 16],
        'menueDepenses' => [parent::class, 'menueDepenses', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'photos' => [parent::class, 'photos', null, 16],
        'plainPassword' => [parent::class, 'plainPassword', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'statutOccupation' => [parent::class, 'statutOccupation', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
