<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MenueDepense extends \App\Entity\MenueDepense implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acheteur' => [parent::class, 'acheteur', null, 16],
        "\0".parent::class."\0".'copropriete' => [parent::class, 'copropriete', null, 16],
        "\0".parent::class."\0".'dateAchat' => [parent::class, 'dateAchat', null, 16],
        "\0".parent::class."\0".'descriptionUsage' => [parent::class, 'descriptionUsage', null, 16],
        "\0".parent::class."\0".'designation' => [parent::class, 'designation', null, 16],
        "\0".parent::class."\0".'fournisseur' => [parent::class, 'fournisseur', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'photos' => [parent::class, 'photos', null, 16],
        "\0".parent::class."\0".'prixUnitaireHt' => [parent::class, 'prixUnitaireHt', null, 16],
        "\0".parent::class."\0".'prixUnitaireTtc' => [parent::class, 'prixUnitaireTtc', null, 16],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'totalTtc' => [parent::class, 'totalTtc', null, 16],
        'acheteur' => [parent::class, 'acheteur', null, 16],
        'copropriete' => [parent::class, 'copropriete', null, 16],
        'dateAchat' => [parent::class, 'dateAchat', null, 16],
        'descriptionUsage' => [parent::class, 'descriptionUsage', null, 16],
        'designation' => [parent::class, 'designation', null, 16],
        'fournisseur' => [parent::class, 'fournisseur', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'photos' => [parent::class, 'photos', null, 16],
        'prixUnitaireHt' => [parent::class, 'prixUnitaireHt', null, 16],
        'prixUnitaireTtc' => [parent::class, 'prixUnitaireTtc', null, 16],
        'quantite' => [parent::class, 'quantite', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'totalTtc' => [parent::class, 'totalTtc', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
