<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Photo extends \App\Entity\Photo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'badge' => [parent::class, 'badge', null, 16],
        "\0".parent::class."\0".'batiment' => [parent::class, 'batiment', null, 16],
        "\0".parent::class."\0".'copropriete' => [parent::class, 'copropriete', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'incident' => [parent::class, 'incident', null, 16],
        "\0".parent::class."\0".'menueDepense' => [parent::class, 'menueDepense', null, 16],
        "\0".parent::class."\0".'nomFichier' => [parent::class, 'nomFichier', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'badge' => [parent::class, 'badge', null, 16],
        'batiment' => [parent::class, 'batiment', null, 16],
        'copropriete' => [parent::class, 'copropriete', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'incident' => [parent::class, 'incident', null, 16],
        'menueDepense' => [parent::class, 'menueDepense', null, 16],
        'nomFichier' => [parent::class, 'nomFichier', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
