<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Document extends \App\Entity\Document implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'copropriete' => [parent::class, 'copropriete', null, 16],
        "\0".parent::class."\0".'createur' => [parent::class, 'createur', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'file' => [parent::class, 'file', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nomFichier' => [parent::class, 'nomFichier', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'visibilite' => [parent::class, 'visibilite', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'copropriete' => [parent::class, 'copropriete', null, 16],
        'createur' => [parent::class, 'createur', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'file' => [parent::class, 'file', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nomFichier' => [parent::class, 'nomFichier', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'visibilite' => [parent::class, 'visibilite', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
